name: panorama
description: Panorama -- A 360-degree panorama viewer.
version: 0.4.1
homepage: https://github.com/zesage/panorama
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube:
  motion_sensors:
    git:
      url: https://github.com/deckerst/aves_panorama_motion_sensors.git
      ref: aves

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
